"""add cascade delete

Revision ID: 907219cb1b9e
Revises: dea4da7c2081
Create Date: 2024-06-18 19:47:24.020719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '907219cb1b9e'
down_revision: Union[str, None] = 'dea4da7c2081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_sender', sa.Integer(), nullable=False),
    sa.Column('id_chat', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_chat'], ['chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('message')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_sender', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_chat', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_chat'], ['chat.id'], name='message_id_chat_fkey'),
    sa.PrimaryKeyConstraint('id', name='message_pkey')
    )
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
